manifest_version = 2
name = "OpenAPI Validation (JS)"
description = "Application template for validating requests against an OpenAPI document."
authors = ["<oss@fastly.com>"]
language = "javascript"

[setup]
  [setup.backends]
    [setup.backends.origin]
      description = "Application origin"
      address = "httpbin.org"
      port = "443" # HTTPS. Use 80 for HTTP.

[local_server]
  [local_server.backends]
    [local_server.backends.origin]
      url = "https://httpbin.org/"
  