# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["<oss@fastly.com>"]
description = "Application template for validating requests against an OpenAPI document."
language = "javascript"
manifest_version = 2
name = "OpenAPI Validation (JS)"

[local_server]
  [local_server.backends]
    [local_server.backends.origin]
      url = "https://httpbin.org/"

[scripts]
  build = "npm run build"

[setup]
  [setup.backends]
    [setup.backends.origin]
      address = "httpbin.org"
      description = "Application origin"
